# FIX: Changed 'yourhelp' to 'yourhelpa' in the path
deployment:
  tasks:
  - export DEPLOYPATH=/home/yourhelpa/public_html 
  - /opt/cpanel/ea-nodejs18/bin/npm install
  - /opt/cpanel/ea-nodejs18/bin/npm run build
  - /bin/cp -r build/* $DEPLOYPATH