const fs = require('fs');
const path = require('path');

// Generate js/config.js during build from environment variables.
// This file will be deployed as part of the static site so runtime JS can read
// window.SUPABASE_URL and window.SUPABASE_ANON_KEY.

const outPath = path.join(__dirname, '..', 'js', 'config.js');

const SUPABASE_URL = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.warn('\n[generate-config] Warning: SUPABASE_URL or SUPABASE_ANON_KEY is not set in the build environment.');
  console.warn('[generate-config] The generated js/config.js will contain empty values — authentication will fail in production.\n');
}

const content = `// Auto-generated by scripts/generate-config.js
// Do not commit secrets to source control. Set SUPABASE_URL and SUPABASE_ANON_KEY in your CI/Vercel dashboard.
window.SUPABASE_URL = '${SUPABASE_URL}';
window.SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content, { encoding: 'utf8' });
console.log('[generate-config] Wrote', outPath);
